### ISSUE TITLE
Newlines in the generated code

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#110]
In the first version of the C formatter for generated code, we would ignore blank lines inside C functions. Later, I changed the behavior to merge blank lines instead of removing them outright. This lets us use blank lines for formatting. For example, I like how the current luaopen function separates blocks of initializers with an empty line
  
    lua_pushstring(L, "check_nil");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    
    lua_pushstring(L, "check_boolean");
    lua_geti(L, closures, 3);
    lua_settable(L, export_table);
    
The downside is that the coder.lua has to be very careful about not generating a \n when it doesn't want to create a blank line. For example, there are places where we put the `]]` of a string literal on the same line instead of on a line of its own and there are times where we avoid adding empty strings to the `parts` array because the `table.concat(parts, "\n")` would add an extra `\n`.

Another option we could go with is to come up with a special sequence to denote the empty lines that we actually want to show up. For example, we could have lines with a `/*BLANK*/` comment be rendered as a blank line, and other blank lines be ignored. Or we could change the heuristic to collapse two blank lines into a single blank line but skip a blank line if it appears alone. In either of these cases the C formatting function would cease to be indempotent, but perhaps that is a better than having to deal with finnicky \n in the coder.lua?

**Comment by gligneul** [comment]
Coulnd't we add a special comment such as `/* --- */` in the places that we want explicit blanks? We could also add a non C symbol to represent a blank line, such as `@blank`.

**Comment by gligneul** [comment]
> Or we could change the heuristic to collapse two blank lines into a single blank line but skip a blank line if it appears alone.

I think that is too clever.
