### ISSUE TITLE
Be more strict about __len metamethod

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#114]
Pallene currently violates the "gradual guarantee" when computing the length of an array. If the array has a __len metamethod, both Lua and Pallene might compute different values.

Pallene function:

```lua
function p_len(xs:{value}): integer
    return #xs
end 
```

Lua function:

```lua
function l_len(xs)
    return #xs
end 
```

Testcase

```lua
xs = {}
setmetatable(xs, { __len = function(self) return 42 end })
print(p_len(xs)) -- 0
print(l_len(xs)) -- 42
```

A possible fix could be to have Pallene produce an error when evaluating `#xs` if the table has a __len metamethod. Or perhaps it could be even stricter, forbidding metatables outright.

If we do this it would be a good idea to measure the performance impact. A good test case might be the the `xs[#xs + 1]` idiom for adding elements to the end of an array, since it calls `#` in the innermost loop.

**Comment by gligneul** [comment]
This issue also applies to other metamethods. For instance, we ignore
`__index`/`__newindex` and perform raw operations instead.

I'm afraid that checking whether a table has specific metamethods will add
a noticeable overhead. It might be better to only check whether there is a
metatable or not. Moreover, we might be able to reduce the overhead by
checking only once after a Lua boundary.

If possible, I would also like to pass a command line flag to the compiler
to remove these kind of checks.

Yet another option is to give full support to metatables for types with a
given annotation. It would be up to the user whether a given type ignores
or respects the metamethods.
