### ISSUE TITLE
Add license information to all files

### ISSUE THREAD

**Issue by gligneul** [pallene-lang/pallene#117]
It should be simple to include the SPDX identifier to all our source files.
https://spdx.org/ids-how

**Comment by hugomg** [comment]
We'd need to add a short human-readable copyright notice next to those machine -readable identifiers. Fo you have a suggestion of how those could look?

**Comment by gligneul** [comment]
We could add the copyright in the line after:
```
-- SPDX-License-Identifier: MIT
-- Copyright (c) 2018, The Pallene Developers
```
Also, I think we should track which files came from Titan and should have their copyright and which files we created ourselves.

**Comment by hugomg** [comment]
I'd prefer putting the human-readable info first. What about he following?

```
-- Copyright (c) 2018, The Pallene Developers
-- Pallene is licensed under the MIT license.
-- Please refer to LICENSE.txt and AUTHORS.txt for details
-- SPDX-License-Identifier: MIT
```

**Comment by hugomg** [comment]
> Also, I think we should track which files came from Titan and should have their copyright and which files we created ourselves.

I'm not sure there is much to gain by doing this. By now, significant chunks of the code have been rewritten but at the end of the day most of it has evolved from the original titan stuff.

**Comment by gligneul** [comment]
> I'm not sure there is much to gain by doing this. By now, significant chunks of the code have been rewritten but at the end of the day most of it has evolved from the original titan stuff.

Agreed, the copyright in the main license file should suffice.

**Comment by gligneul** [comment]
> I'd prefer putting the human-readable info first. What about he following?

That seems fine.
