### ISSUE TITLE
Add DCO to project

### ISSUE THREAD

**Issue by gligneul** [pallene-lang/pallene#119]
If we are willing to receive outside contributions, I think we should add DCO to the project.
https://developercertificate.org/

**Comment by gligneul** [comment]
We could also add a contributing file:
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by hugomg** [comment]
I think a DCO is a bit overkill for us. The default "inbound=outbound" logic should be sufficient. 

If the goal is to make the license clearer I would just add a small section about it in the README.

**Comment by gligneul** [comment]
I think the purpose of the DCO is a little different. The only hassle would be to sign off the commits.
We could leave this open on hold until we start getting more outside contributions.

**Comment by hugomg** [comment]
My understanding is that in the absence of a DCO it is generally understood that inbound contributions are licensed under the open source license of the project (known as "inbound = outbound"). I'm not sure the additional bureaucracy would be worth the weight, at least for now.
