### ISSUE TITLE
Implement a backend that generates code compatible with the C-API

### ISSUE THREAD

**Issue by gligneul** [pallene-lang/pallene#126]
Instead of generating code that accesses the internal data structures of the Lua interpreter, this new backend should generate code that is compatible with the C-API. I expect this code to be slower than the one that we generate now. However, this code will be useful for performance comparisons published in papers.

To achieve this feature, we could create a new module called by `coder.lua` that encapsulates the specifics of manipulating the Lua state. The module that manipulates the state directly could be called `state.lua` and the one that uses the C-API could be called `capi.lua`.

**Comment by hugomg** [comment]
I am not sure the added code complexity would necessarily be worth it if the only goal were to run benchmarks and experiments. Benchmarks only need to be written once, so it's no so bad if you need to do it by hand.

That said, I think a pure C-API backend could be useful as a solution that does not depend on unstable and less-portable Lua internals.

**Comment by hugomg** [comment]
At the moment I think it is better for us to focus on the existing C backend. We can always reconsider in the future, if circumstances change.
