### ISSUE TITLE
Implement % operator for floating point numbers

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#149]
Currently, Pallene implements the `%` operator for integers, but not for floating point numbers. The following test case currently crashes the compiler with a "not implemented" exception:

```
function f(a: float, b: float): float
    return a % b
end
```

To implement this we would need to add a case inside `gen_cmd["Binop"] ` in coder.lua to generate the appropriate C code for the FltMod operation. The simplest implementation would be to call the luaV_modf function from lvm.c

It might also be worthwhile to test the performance of re-exporting the luaV_modf function as an `static_inline` function in pallene_core.h

We should also remember to add the appropriate test case in `coder_spec.lua`. We should also add more non-integer floating point numbers to `coder_test_operators.lua` to ensure that the tests for the `%` operator cover all the cases.

**Comment by ahmedkrmn** [comment]
Will start working on this and submit a PR once finished.

**Comment by hugomg** [comment]
This one might be a bit more fun :)

**Comment by ahmedkrmn** [comment]
Ok, will start with this!
