### ISSUE TITLE
Improve record tag error messages to include the record name

### ISSUE THREAD

**Issue by gligneul** [pallene-lang/pallene#151]
The issue can be found in the following test case in `coder_spec.lua`:
```
        it("check record tags", function()
            -- TODO: change this message to mention the relevant record types
            -- instead of only saying "userdata"
            run_test([[
                local prim = test.make_prim(123)
                local ok, err = pcall(test.get_x, prim)
                assert(not ok)
                assert(string.find(err, "expected userdata but found userdata",
                        nil, true))
            ]])
        end)
```

**Comment by Akylzhan** [comment]
I can work on this issue, as I understood I need to replace the message with ```string.format("expected userdata but found $s", type(prim))``` ?

**Comment by gligneul** [comment]
It is not that simple because `type(prim)` will return only the string `"userdata"`. You have to retrieve the record type at runtime. Given these definitions in Pallene:
```
record circle float x; float y; float radius end
record square float x; float y; float length end
function area(s: square): float
  return s.length ** 2
end
```
If I call the function `area` passing a circle or a string, I would like to see the following error messages:
```
m.area("foo") --> "expected record square but found string"
m.area(circle_obj) --> "expected record square but found record circle"
```

**Comment by hugomg** [comment]
One direction we could go would be to store the name of the record type in the __name field of its metatable, as is done by luaL_newmetatable.

We'd also have to change pallene_tag_name and/or pallene_runtime_tag_check_error, to correctly work with these record type names. 

We might want to check if it would make sense to use luaT_objtypename to get the type name. I wasn't aware of this function when I originally wrote pallene_type_name.
