### ISSUE TITLE
Implement table field names longer than 40 characters

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#154]
The current implementation of table fields only works with table fields of up to `LUAI_MAXSHORTLEN` bytes (40).

Very long field names like this are exceedingly rare so this isn't a high-priority feature, and it isn't important that the implementation be very efficient either.

**Comment by gligneul** [comment]
It is important that lengthy fields doesn't affect the performance of normal-sized fields; the differentiation should be solved during compile time.
Anyway, I don't think it is worth to implement lengthy fields due to the extra complexity in the compiler.

**Comment by hugomg** [comment]
I'm not sure the complexity would be very high, because we woudn't be optimizing this implementation like we did with the short strings. But I agree with you that this is not a big priority.

To be honest, the thing that actually bothers me more is that currently the limit of 40 that Pallene uses does not necessarily match with the `LUA_MAXSHORTLEN` that the C code sees, as I discuss in #153.

**Comment by gligneul** [comment]
> To be honest, the thing that actually bothers me more is that currently the limit of 40 that Pallene uses does not necessarily match with the LUA_MAXSHORTLEN that the C code sees, as I discuss in #153.

We would still have this problem because we would need to know this constant during the compilation of a Pallene module. If we have the path of the Lua source code inside the compiler, we could obtain this value appropriately.

**Comment by hugomg** [comment]
> We would still have this problem because we would need to know this constant during the compilation of a Pallene module.

Not necessarily. We generate the code using ifdefs and let the C preprocessor take care of it.

**Comment by ahmedkrmn** [comment]
@hugomg How do you think I approach this?

You said there's a problem with the Pallene implementation because the limit it uses does not necessarly match with `LUAI_MAXSHORTLEN`. 
Is this what the issue is aiming to fix? Or are you looking to remove that limit and put no bound on the table field size?

**Comment by hugomg** [comment]
The first problem we are trying to fix is that Pallene currently outright rejects record fields with long names. If you look in checker.lua, line 165, you'll see that it is producing an error message in that case. 

The initial fix would be to move this if statement to the coder.lua. If the length of the field name is ≤ 40, then we use the current implementation, which is specialized for "short strings". It the length of the field name is > 40, then we need to create a new implementation, which should call luaH_getstr instead of pallene_getshortstr.

The second problem is that the hardcoded limit of 40 that we are using in the Pallene compiler does not necessarily match the value of LUAI_MAXSHORTLEN which is defined in llimits.h. But we can worry about that later. One possible workaround for this second issue would be to use ifdefs in the generated C code.

> And is this issue only related to table fields or it applies on any string in general?

It is only related to accessing named fields in Pallene records, which are Lua tables with string keys. Currently, Pallene only allows fields with ≤ 40 characters.

**Comment by hugomg** [comment]
Fixed by #176
