### ISSUE TITLE
Test suite creates temporary files in current working directory

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#17]
Currently, the test suite creates a bunch of temporary files in the current working directory: test.titan, test.so, test_output.txt, etc. It would be better to create these files in a temporary directory instead, to avoid potentially overwriting files in the current directory.

It might also be a good idea to modify the driver to put intermediate files in a temporary directory instead of next to the source code...

Fixing this issue probably depends on fixing #16 first.

**Comment by ahmedkrmn** [comment]
Hi, isn't that similar to what we did in #160?

**Comment by gligneul** [comment]
Yes, it is similar but for the tests. Currently, if I have file called `test.pln` in the root folder of the project this file is overwritten when I run the tests.

**Comment by ahmedkrmn** [comment]
Alright, will start working on it!

**Comment by hugomg** [comment]
The generated test file is loaded by the Lua test script using "require", so it needs to stay in the current working directory, at least for now.

That said it would be nice if the test suite it didn't clash with files named test.lua or test.pln, because those are both common file names for someone trying out Pallene for the first time.

The long term solution would be to run tests in a separate directory, but that requires fixing #16 first.

One simple workaround for now might be to rename the test file to "_test.pln" instead of "test.pln", or something like that.

Another thing that could help would be to check if the file names we will use for the tests are already present in the current working directory. That way we can abort the test suite before it erases the user's files.

**Comment by ahmedkrmn** [comment]
@hugomg what about using `os.tmpname()` ?

**Comment by ahmedkrmn** [comment]
Also regarding checking if a file with the same name exists, the `util.set_file_contents()` function is used in multiple functions, should this check be done in all of them?

**Comment by hugomg** [comment]
I think the decision of whether to check if we are overwriting something has to do with how we choose the name of the file, and not with whether it uses set_file_contents.

When the file name is provided by the user, then it is OK if we overwrite the file. But if we are the ones coming up with the file name then we have to make sure that we aren't overwriting anything. One way is asking the OS to give us an unused temporary file name. In this particular case we can't do that, and are forced to use a hardcoded name, so adding an extra check to see if the file doesn't exist would let us be extra safe.

**Comment by hugomg** [comment]
Unfortunately, I don't think we can use os.tmpname because our compiler requires that pallene files have a "pln" extension and Lua requires that the generated libraries have a ".so" extension.

If we really wanted there might be ways to avoid these two limitations but I'm not sure that they would be worth the trouble, considering that the original problem will go away once we finally implement #16.
