### ISSUE TITLE
It would be nice to have an automatic way to convert Pallene into Lua.

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#173]
With a bit of work, it should be possible to convert Pallene modules into Lua by removing the type annotations.

1. It would let us check if our unit tests are obeying the "gradual guarantee".
2. In the benchmarks that don't use LuaJIT features, we could generate the Lua version of the code from the Pallene version.

**Comment by gligneul** [comment]
This should be a separate compiler. If the front-end were a lib, the actual compiler and the faux compiler could use the same frontend and just generate different code base on the AST. Moving the fronted to a lib would also make easier to implement plugins to editors.

**Comment by gligneul** [comment]
This would be a nice GSoC project.

**Comment by itssamuelrowe** [comment]
@hugomg Should we close this issue?

**Comment by hugomg** [comment]
Absolutely! Thanks, Samuel :)
