### ISSUE TITLE
We should check at module-load time if the runtime library version is correct

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#18]
When a Pallene library is linked with a version of the runtime library that is not the same version that it was compiled for, it is very easy to get segmentation faults at execution time. We should protect against this by checking the library versions at module-load time.

To do this we would need some way to represent the library version at runtime. Would adding a `RUNTIME_VERSION` in `tcore.h` be good enough?

**Comment by gligneul** [comment]
`RUNTIME_VERSION` should be enough. However, we should only worry about this when we release a version. This is a minor issues for devs.

**Comment by ahmedkrmn** [comment]
@gligneul Do you suggest working on this now or leaving it for later since you've said it's a minor issu?

**Comment by hugomg** [comment]
Now that I think about it, I'm not sure if adding a RUNTIME_VERSION will help with development, since it is very easy to firget to increment the version when making other changes to the library.

It might be more useful once we release a stable version of Pallene, but we can think about the proper approach when we get to that point.

For now, I feel like we can leave this open, but I'm removing the "good first issue" tag.

**Comment by gligneul** [comment]
@hugomg we don't need to update the variable every time we change the file, just when we release a new Pallene versions. What would be a proper approach?

**Comment by hugomg** [comment]
My original motivation for opening the issue was that, during development, sometimes I'd forget to recompile the library after making changes to it.

But yes, from the point of view of an user using a release of Pallene, it eould only need yo be updated when a new release is made.

**Comment by gligneul** [comment]
I'm marking this as a discussion since it is not clear what should be done. I'm thinking about creating two new issues, one to solve the release problem, which should be simple, and another one to solve the dev problem, which I don't have a solution in mind yet. What do you think?
