### ISSUE TITLE
The output of the type checker should not be an ir.Module

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#191]
Currently the type checker also converts the toplevel of the program from an AST representation to a lower level ir.Module representation. IIRC, the original motivation for why I did this is that was because it was convenient to use checker.Name to describe the results of our scope analysis in a way that the IR can see it.

However, the tight coupling between the type checker and the IR generator has been a recurrent source of headaches, and an impediment for work on the IR such as #150. We should consider refactoring the type checker so that it does not depend on the IR.

I don't know what would be the ideal way to do this but I'm opening this issue so we have a place to discuss it.

**Comment by gligneul** [comment]
Couldn't we just create the IR module in the `to_ir` pass and use the symbol table for everything we need in the checker?

**Comment by hugomg** [comment]
The source of the problem is that the to_ir needs to use the symbol table to associate Pallene variables with C variables. Currently we already start thinking about the "C variables" in the checker, because the _checker stores that info in the _name field.

My hunch is that the checker shouldn't be touching this kind of concept. So we'd have to come up with a different way to pass to symbol table info to to_ir.

**Comment by gligneul** [comment]
Couldn't `to_ir` create another symbol table to track the C variables?

**Comment by hugomg** [comment]
Yes, one option would be to throw away the symbol table that we create on the checker and create a new one in to_ir. That is, the to_ir would create its own symbol table, using `with_block` in a way that mirrors what the checker does. There would be no `_name` field anymore.

**Comment by gligneul** [comment]
I think that is a good idea even though there will be a little bit of code repetition.
