### ISSUE TITLE
Support for warning messages

### ISSUE THREAD

**Issue by leokaplan** [pallene-lang/pallene#198]
Currently there is just support for dump messages and error messages. Sometimes there are messages that are important for the end user but shouldn't stop the compilation process (e.g. outputs of #194 ).

**Comment by hugomg** [comment]
I feel like this discussion would benefit from concrete examples of desirable compiler warnings, instead of discussing warnings in a vacuum.

**Comment by hugomg** [comment]
I'm closing this because there are no plans to implement this feature at the moment. Of course, we can always reconsider if the need for warnings shows up.
