### ISSUE TITLE
Should we show a better stack trace instead of error("impossible")?

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#225]
At the end of and if-else-if chain we use `error("impossible")` to mark a type error when someoone passes in the wrong kind of table.

```
local tag = exp._tag
if tag == "ast.Nil" then
    handle_nil()
elseif tag == "ast.Exp.Bool" then
    handle_bool()
-- ...
else
    error("impossible")
end
```

The problem is that whenever the `error("impossible")` happens, we don't get any information about what was the tag that caused the problem. To debug we typically have to add a temporary "print" statement.

I propose that we create a new helper function to show a better error message for these errors. One option would be something like `typedecl.tag_error(tag)`.

**Comment by hugomg** [comment]
If we implement this, don't forget to grep for all uses of the words error and impossible. There are some variations in the codebase such as `error(tag .. " impossible")`.

**Comment by inJuly0** [comment]
Hi there, after taking a thorough look at the Pallene's Lua front end, I'd like to work on this issue.
I'm assuming the issue refers to places like this one for example, in `types.lua`: 

```lua
function types.indices(t)
    local tag = t._tag
    if     tag == "types.T.Table" then
        return t.fields

    elseif tag == "types.T.Record" then
        return t.field_types

    else
        error("impossible")
    end
end
```

more specifically, the `error("impossible")` at the end ?

I'd like to propose an idea that a more descriptive error message would be easier to debug. Say, for example we could do :
`typedecl.tag_error(tag, "cannot index type.")`

which would  then show a proper error message like `Boolean: cannot index this type.`
the second argument to`typedecl.tag_error` could be optional, and an "impossble" is thrown in it's absence.

An even further improvement (in my opinion) could be an optionally interpolated 2nd argument, like so:
`typedecl.tag_error(tag, "cannot index type ${tag} .")`.

This is similar to what I've been using to debug internal compiler errors and type errors in my langauge, and I think it would be a good fit for Pallene too. :)

**Comment by hugomg** [comment]
We appreciate any help here :)

> I'm assuming the issue refers to places like `error("impossible")`

Exactly!

> I'd like to propose an idea that a more descriptive error message would be easier to debug.

I think the thing that would help the most is if the `tag_error(tag)` function included the tag in the error message, instead of just saying "impossible".

>Say, for example we could do `typedecl.tag_error(tag, "cannot index type.")`

In this particular example, the `error("impossible")` is taking care of two kinds of errors

1. The `t` is a `types.T` but it is not an indexable type
2. The `t` isn't a `types.T` at all. It might be a table that doesn't have a `_tag` or has a different kind of tag.

The second one is probably more common than the first one. The most common reason for hitting an `error("impossible")` is if we accidentally passed the completely wrong object to the function. The second most common reason is if we add a new case to the tagged union in ast.lua or types.lua but forget to add an `elseif` in one of the functions that uses it.

However, I do like your suggestion for a better error message in the types.indices function. Maybe we could add a separate elseif for it?

```lua
function types.indices(t)
    local tag = t._tag
    if     tag == "types.T.Table" then
        return t.fields

    elseif tag == "types.T.Record" then
        return t.field_types
 
    elseif type(tag) == "string" and string.find(tag, "types.T", 1, true)
        error(string.format("%s is not an indexable type", tag))

    else
        util.tag_error(tag) -- the thing isn't a type at all
    end
end
```

We could even make another helper function to help with that. There are a handful of places in the code where we are doing variations of `string.match(tag`, which would be a  bit cleaner if we did this. For example, line 120 in uninitialized.lua.

```lua
function typedecl.tag_matches(tag, tag_prefix)
   return type(tag) == "string" and string.find(tag, tag_prefix, 1, true) ~= nil
end
```

**Comment by inJuly0** [comment]
> In this particular example, the error("impossible") is taking care of two kinds of errors

Ah, I understand.

Yes, that sounds pretty good to me. so I guess I can start working on it ?

(on a side note, I got Pallene up and running on my Manjaro laptop, I was wondering if it can be built on windows ? just curious since I mostly use my windows PC and there doesn't seem to be a separate make target for it)

**Comment by hugomg** [comment]
> Yes, that sounds pretty good to me. so I guess I can start working on it ?

Sure! And feel free to ask any questions if you need to...

 > I was wondering if it can be built on windows ?

In theory it should be possible to get Pallene to run on Windows because the kind of C code we generate is similar to the kind of C code used by the Lua interpreter and that code works on Windows. However, none us know Windows very well so we never added a Makefile target for it. Contributions on that direction would be welcome. See issue #322.
