### ISSUE TITLE
Assigning to builtins should not be allowed

### ISSUE THREAD

**Issue by itssamuelrowe** [pallene-lang/pallene#232]
The compiler generates "type error: attempting to assign to builtin function io_write" for the following source code:
```
function f(x: string)
end

function g()
    io_write = f
end
```

With the following source code, it generates "expected function but found function in assignment".
```
function f(x: integer)
end

function g()
    io_write = f
end
```
With respect to the second code snippet, the compiler is complaining that `f` does not have a type that is compatible with `string -> ()`, which is the shape of `io_write`. Compatibility means that the function types have to be identical except that any is compatible with any other type. (The error message in the second case is vague and is explained here: https://github.com/pallene-lang/pallene/issues/231)

In any case, the compiler must always generate an error when assigning to builtins, even if the function you are trying to assign is the wrong type. This has to do with the order that we call `type_error`.

Further, it seems that we do not have any test cases for this. We should have add test cases for assigning builtins to `checker_spec.lua`.

**Comment by hugomg** [comment]
This problem also happens with non-builtin functions. The error we want for the following test case is "attempting to assign to toplevel constant function". Currently it also says "expected X but found Y in assignment".

```
function f(): float
    return 3.14
end

function test(g: () -> integer)
    f = g
end
```
