### ISSUE TITLE
Should we replace the LPeg parser with a recursive descent parser?

### ISSUE THREAD

**Issue by itssamuelrowe** [pallene-lang/pallene#262]
This issue lists out all the pain points we have encountered so far with the parser. If we ever do rewrite the parser, knowing exactly what are the pain points that we want to solve would let us make more informed decisions later.

Some pain points currently include:
 * Contributors have to learn LPeg.
 * The parser and the lexer are hard to debug.
 * The lexer is embedded in the parser.
 * Some tokens such as comments are discarded. If we ever implement document generators, linters, and other such tools we could reuse existing code base if the lexer emitted hidden tokens on a different channel, in other words, a multi-channel lexer.  
 * Finding locations for tokens, sometimes, means we have to edit the parser.
 * Pallene exits after encountering a single syntax error. With a handwritten parser, we could implement error recovery strategies. However, we should also take into consideration that we are using an extended version of LPeg called lpeglabel, which has support for error recovery. But currently we are only generating errors and never recovering from them. We have not explored the question of whether it would be easier to implement error recovery using lpeglabel's error recovery or doing it by hand.

**Comment by hugomg** [comment]
Implemented in #294
