### ISSUE TITLE
In the translator, consider using gsub("%S", "") instead of gsub("%S", " ")

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#277]
If we remove the non-whitespace characters instead of simply replacing them with spaces it might produce more pleasant-looking output. For example,

    function f(x: integer)

could become

    function (x)

instead of 

    function f(x         )

Column numbers would not be preserved but line numbers would still be preserved. I think this might be OK. IIRC, Lua error messages don't show column numbers, they only show line numbers.

**Comment by hugomg** [comment]
Fixed by #303.

**Comment by bjornbm** [comment]
> Column numbers would not be preserved but line numbers would still be preserved. I think this might be OK. IIRC, Lua error messages don't show column numbers, they only show line numbers

I was about to write an issue suggesting the original behavior, to get the column numbers. For “cheap” editor support, I am considering running `--emit-lua` and then, for example, run _luacheck_ on the lua file(s) and use this to drive the editor (for example, [neo]vim quickfix functionality). Maybe _lua-ls_ (sumneko) could be jury-rigged to be useful for Pallene in a similar fashion (roundtripping via `--emit-lua`).

Also, the fact that Lua itself doesn't show column numbers  is perhaps an implementation detail that could change in the future?

Anyway, in my opinion not much was won by removing the spaces, while potential for some tooling reuse was lost. If the more pleasant-looking output is important maybe keep `--emit-lua` as it is and add `--emit-lua-preserve-columns`?

**Comment by hugomg** [comment]
Hmm, now that's an use case I something I hadn't thought about!

I suppose that a command flag to tell pallenec to only type-check the program, without emitting a C or Lua file, might be helpful. I cooked up a quick one over on PR #566. Could you please check if it is useful for your purposes?

As for the column numbers in --emit-lua, maybe it's useful if there are extra error messages you can get from luacheck but not from pallenec. Please feel free to experiment with it and create a PR if it turns out to be a good idea. (I do like the current pleasant-looking output though, so my vote is for a  separate flag or configuration option). I only ask that if you do so, open a new issue instead of commenting on this one. It's easier for me to find the discussion if it's under a recent and open issue.
