### ISSUE TITLE
Implement the `--module` or `-m` flag

### ISSUE THREAD

**Issue by itssamuelrowe** [pallene-lang/pallene#312]
The `-m` or `--module` can be used to say "place the output in this module". This allows us to place output in appropriate modules, this could prove to be really useful when we are invoking the compiler from scripts. This flag should accept the module name instead of the path to the output file. This way we would not have to explicitly mention the extension of the generated output.

For example,
```
./pallenec test.pln -m xyz --emit-lua
```
should generate
```
xyz.lua
```

```
./pallenec test.pln -m abc.xyz
```
should generate
```
abc/xyz.so
```

Notice that we use `.` instead of `/` in the module name. In the above example, `-m abc.xyz` instead of abc/xyz. This is inspired by the format which we use to specify module names to `require` in Lua.

**Comment by hugomg** [comment]
Closing this in favor of #321. Since the modname is tied to the file name, we have the option of specifying one or the other, but not both. For example, it wouldn't make sense to do something like `./pallenec x.pln -o y.so -m z`.
