### ISSUE TITLE
Implement a -o flag

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#321]
Allow the programmer to choose the output filename. This should work when Pallene is called without any flags or when it is called with one of the `--emit-x` flags:

```sh

# When called without any flags, pallenec outputs a benchmarks/matmul/pallene.so by default.
./pallenec benchmarks/matmul/pallene.pln

# The -o flag let's us specify the output file name directly.
./pallenec benchmarks/matmul/pallene.pln -o benchmarks/matmul/pallene.so

# It should also work with the --emit-lua flag. When the -o flag is provided, the modname
# (benchmarks.matmul.lua) should be inferred from the output filename.
./pallenec --emit-lua benchmarks/matmul/pallene.pln -o benchmarks/matmul/lua.lua
```

**Comment by srijan-paul** [comment]
Hi, I was looking for something similar and came across this issue. I'll be hacking on this a bit and update via a PR if I end up doing it :D 

Other than that,
Do you think it would help if we could also compile files as batches (similar to what typescript does for example)? 
My idea was to add a `pallene-config.json` file in the root directory and then simply calling `./pallenec <dir-path>` would compile all the files in t`<dir-path>` to the output folder mentioned in the config file. 
I think this would be helpful for end users (as I am finding it a bit tedious to write a bash script to compile and move files and I don't think there many options at the moment).

I understand that this might not be the main focus on development at an early stage of the language, so I was thinking I'll implement this as a separate standalone tool in my engine, that would call the Pallene compiler, or maybe develop this on a fork of Pallene and make that a PR when/if I feel that it's ready for that purpose.

In case that ends up happening, I wanted to ask if this project would be open to that suggestion. Cheers!

**Comment by hugomg** [comment]
Nice, let me know if you run into any problems along the way.

I'm not intimately familiar with TypesScript but those tsconfig.json files remind me of Luarocks rockspec files. In addition to being a package manager, Luarocks is also a build tool. I have a feeling that the most natural way to implement that tsconfig-like functionality would be to figure out how to make Pallene play nice with Luarocks.
