### ISSUE TITLE
Toplevel simplification

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#33]
Currently, the Pallene toplevel is a list of declarations, which can be either type, variable or function declarations.

I propose to modify it so variables must be constants and that declarations must be in order:

    <type declarations>
    <constant variable declarations>
    <function declarations>

The motivation for this is as follows:

1. We would be able to re-introduce letrec for type and function declarations.

The main motivation for avoiding letrec before was that it didn't fit well with intermixed variable and function declarations and that it was incompatible with Lua. Forcing an order for the variables avoids the first issue. For the second issue, there are ways to implement an "imperative toplevel" that are more compatible with Lua but I don't feel like commiting to implementing this, at least for the short term.

2. Only having constant variables in the toplevel would simplify the code

We would only need to pass around the array part of the upvalues_table, and not the upvalues_table itself. (This has to do with how the write barriers work)

We would also be able to get rid of the current concept "upvalues" in the compile and transform it in a pass that operates at the "variable level". String literals are promoted to global variables. Numeric global constants can be deleted and substituted in the function bodies, similar to "#define".

3. Having the toplevel only contain constant expressions would simplify the logic in the module's "luaopen" function.

Right now, the coder treats the toplevel as a special kind of function body (notice how it passes around a Context while going through it), which has proven to be finicky in the past.

Going forward, getting rid of the imperative aspects of the toplevel would help with the intermediate representation, since it would only need to worry about representing the internals of Titan functions, and not also the toplevel.

**Comment by gligneul** [comment]
> must be in order
Is this a thing in any language?

> Only having constant variables in the toplevel would simplify the code
This would oversimplify the language. We would eventually just adding variable variables back in the future, so I don't see a reason to remove this feature now.

> Going forward, getting rid of the imperative aspects of the toplevel would help with the intermediate representation, since it would only need to worry about representing the internals of Titan functions, and not also the toplevel.
I'm not totally against this part. Variables in the top level could be initialised with literals, so there won't be a need for a IR.
Eventually we could have a kind of macro system for constant expressions.

**Comment by hugomg** [comment]
This kind of simplification would be too restrictive for little gain.
