### ISSUE TITLE
PEP: Get rid of export and mutually-recursive functions

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#344]
The problem
===========

Talking with Roberto, one thing that is currently a bit problematic about Pallene is that some of the toplevel syntax is incompatible with Lua. There are two main sticking points that I can think of right now. The first is that we use `export` syntax for exporting functions from a module.

    export function foo(): integer
        return 42
    end

The second is that functions declared next to each other can be mutually recursive.

    local function even(n: integer): boolean
       return (n == 0 then
           return true
       else
           return odd(n-1)
       end
    end

    local function odd(n: integer): boolean
       if n == 0 then
           return false
       else
           return even(n-1)
       end
    end

Modules
=======

For functions it should be possible to get rid of the special export syntax by reusing existing Lua design patterns. I think the best proposal we've had in this direction is @gligneul's "module_decl" proposal from #184. This is an attempt to flesh that out.

    local m: module = {}

    function m.f(): integer
        return 42
    end

    function m.g(): integer
        return m.f() + 2
    end

    return m

Every Pallene module should start with a a line at the top that says `local <name>: module = {}` and should finish with a line that says `return <name>`. Public functions are declared using `function <name>.f()` and must be called using the `m.f()` notation as well. Private functions are declared with `local function f()`.

Despite looking like a variable declaration, the module declaration is treated specially by Pallene. Any attempt to use `m` as a value is treated as a compile-time error. Any attempt to use `module` as a type name in a variable declaration is also a compile-time error. It is also an error to try to declare two module tables in the same file.

I propose that we at first reserve the `function m.f() end` notation for adding a public function to the module table. However, once we add lambdas to Pallene we may also allow this notation to be used as a statement, with the usual meaning of `m.f = function() end`.

The `function t:f()` syntax sugar may not be used to declare a public function. However, if we add methods to Pallene/C records we may choose to use this notation to declare public methods.

Mutually recursive functions
============================

The new module syntax would allow us to get rid of the special treatment of mutually recursive functions, at least for the public functions. In the odd and even example, we could have `m.even` call `m.odd`, despite the fact that even is defined before odd.

For mutually recursive private functions we would require new syntax. One option would be use forward declarations just like in Lua.

    local even, odd
    function even(n: integer): boolean end
    function odd(n: integer): boolean end

The type annotation can also go on the forward declaration:

    local even: integer->boolean,
          odd: integer->boolean
    function even(n) end
    function odd(n) end

To make it easy for the compiler to know what function is associated with each name, any attempt to assign a new value to one of the variables used in a forward declaration will be a compile-time error. 

To ensure that the forward-declared toplevel variables are initialized before they are used, the forward declaration must be immediately followed by the function definitions. There may not be other toplevel declarations in between and in particular there may not be any toplevel variable initializers in between, because those contain expressions which may call functions. This restriction may be relaxed in a future version of Pallene. But I would rather leave that for another time, if we ever decide to allow arbitrary statements in the Pallene toplevel.

**Comment by hugomg** [comment]
This issue is an experiment with a new workflow for making changes to the Pallene language. So far, we have treated that as we have treated any other issue or bug; it's just a issue and/or PR on github. However, sometimes that means that not everyone gets to properly discuss the change before it gets merged into the language. And in particular, Roberto doesn't always get a chance to discuss it, because he doesn't look at most of the github issues. So what I'm trying this time is to mark this issue as a PEP to make it explicit that it's about a proposed change to the language, and then ping both the Slack and Roberto's email so everyone can get involved. By the way, I'm calling it a PEP because Pallene also starts with P :)

The rest of this post are things that are still open question for this particular proposal. Once we figure out an answer for them I'll edit them into the rest of the PEP.

New syntax for types
====================

One big question for me is how we should deal with type declarations.  Lua already has patterns for declaring values and functions and for exporting them from a module. But it doesn't have anything of the sort for types. We must think of Lua-compatible ways to declare types and to exporting or import types.

First is the matter of public vs private. If we declare a new type in a Pallene module, either as `typealias` or `record`, should that type always be public or should it be private to the module? If types can be public or private, what should be the syntax for making them public?

    -- Is the Point type public or private to the module?
    -- If it is private, what should be the syntax for exporting it?

    local m: module = {}

    record Point
       x: float
       y: float
    end

    return m

Secondly, how should mutually recursive types work? Currently, we are using the same trick that we are using for functions, where a set of types defined next to each other is allowed to be mutually recursive. If we stop doing that for functions should we also stop doing it for types?  Or is it OK to allow forward references in type definitions, since it's a syntax that doesn't have a Lua parallel anyway?

    -- The "?" in the following example is a nillable type.
    -- Interesting examples of recursive types require something like that.

    record Foo
       next: Bar?
    end

    record Bar
       next: Foo?
    end

Modules that return a value or type
===================================

The other big question for me is how should we deal with modules that don't return a module table. In Lua, sometimes we return a class or a function from a module.  Should we support that in Pallene as well? How would it work exactly?

    local Lexer = require "pallene/Lexer"
    local lex = Lexer.new()
    local tok = lex:next()

**Comment by VictorNogueiraRio** [comment]
@hugomg do you think `module` should be a keyword?

**Comment by hugomg** [comment]
I don't have a strong opinion about whether module should be a keyword. Either option would be fine by me.

**Comment by VictorNogueiraRio** [comment]
> I don't have a strong opinion about whether module should be a keyword. I think either option would be fine.

I also don't have a strong opinion, however, I believe that if it is a valid type, it should be a keyword.

**Comment by hugomg** [comment]
Identifiers are also valid type names, so it doesn't necessarily have to be a keyword. It's also important to remember that technically speaking, `module` is NOT be a valid type. The only place that `module` can be used as a type is in the special declaration for the module table. For example, it should be an error to attempt to declare a local variable of type `module` or to try to create a type that is an array of module.

**Comment by VictorNogueiraRio** [comment]
> Identifiers are also valid type names, so it doesn't necessarily have to be a keyword. It's also important to remember that technically speaking, `module` is NOT be a valid type. The only place that `module` can be used as a type is in the special declaration for the module table. For example, it should be an error to attempt to declare a local variable of type `module` or to try to create a type that is an array of module.

Fair enough.

**Comment by hugomg** [comment]
I wonder if we could avoid this problem by getting rid of the "module" keyword. That is, the programmer would just write something like this:

```lua
local mod = {}
function mod.foo()
end
return mod
```

We would need a way to tell whether an assignment of the form `local <name> = {}` is a module table of if it is a regular variable declaration. One option would be to start the type checking process by looking at the end of the file to see if it ends with a `return <name>` statement. If it does then we assume that the name refers to the module table and we type check the rest of the module accordingly.

**Comment by hugomg** [comment]
In theory we could omit the module table declaration and/or the return statement. If we have a strong requirement that every module always return a module table then we could get rid of the return statement. Similarly, if we have a strong requirement about how the module table should be named, perhaps based on the file name, then we could get rid of the module table declaration.

However, I think I like the idea of having an explicit module declaration and return statement. First, it behaves just like Lua would -- a Lua programer reading the code will know exactly what it does. Secondly, I think it would be nice if in the future we could support modules that return other things. For example, a hello world program without any functions, with all the code written directly in the module toplevel. Another example would be modules that return a type, such as our Location.lua. In that world, having an explicit return statement would be useful. And if we have an explicit return statement then we might as well also have an explicit declaration for the module table.

**Comment by hugomg** [comment]
The new syntax for exporting functions has landed, so I'm closing this.

Some aspects in the discussion, such as exporting types, we can probably discuss separately when we implement those features.
