### ISSUE TITLE
Better error messages for loops with ipairs.

### ISSUE THREAD

**Issue by srijan-paul** [pallene-lang/pallene#348]
Currently, an `ipairs` loop with incorrect number of decls (`for i in ipairs(xs)`) throws an error like so:
```
type error: expected function type (any, any) -> (any) but found function type (any, any) -> (any, any) in loop iterator
```
This is rather confusing as it attributes the error to the iterator function which isn't immediately clear to the user.
It would be better to have an error message that clear says something along the lines of `Expected 2 declarations in loop but found only 1`.

**Comment by hugomg** [comment]
Fixed in #364
