### ISSUE TITLE
Will too many local vars and/or upvalues be a problem for the C compiler?

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#406]
Currently, each separate upvalue becomes a function parameter in the generated C code. Could this cause the C compiler to complain about too many parameters?

1. What is the default limit for local variables and/or upvalues in PUC Lua?
2. What is the minimum limit for function parameters in the C standard?
3. What is the limit for function parameters in GCC and Clang?
4. Are these limits something that the Pallene compiler should worry about?

**Comment by hugomg** [comment]
After running some experiments on my machine, this is what I found:

1. The limit for upvalues is 255 (MAXUPVAL in lfunc.h)
    - The address of an upvalue must fit in an 8-bit VM register
    - This limit is for both Lua and for C closures.
    - I'm not sure why the limit applies to C closures though. Will ask on the Lua mailing list.
2. The C11 standard mandates at least 127 function parameters.
3. gcc can compile at least 1 million function arguments. clang starts raising strange errors at around 100 thousand. Haven't tested actually running these programs though.

As for the last question, I think we don't need to worry about limiting the number of local variables or function parameters, because typical programs are unlikely to reach the C compiler limits.

However, perhaps we should consider respecting the 255 limit for upvalues. While I suspect that the internal APIs would allow more upvalues for a C closure than using lua_pushclosure, I would expect that weird things might happen if we go over the official limit. Furthermore, creating a closure is O(N) on the number of upvalues, but this will not be obvious to most programmers. A hard limit on the number of upvalues could help avoid a performance surprise.

**Comment by hugomg** [comment]
Roberto answered my question in the mailing list. The 255 limit is a hard limit because `nupvalues` in the `ClosureHeader` in `lobject.h` is a byte.

This means that we should certainly enforce an upvalue limit in the Pallene compiler, because the internal APIs (luaF_newCclosure) do not enforce this limit for us. If we try to use more upvalues, it will silently lead to overflow and undefined behavior!

We should be careful about off-by-one errors too. The 255 limit is for the total number of upvalues, including the special `G` upvalue that we add to every closure. Currently, if the function captures N variables we actually create N+1 upvalues. 

We should consider limiting the number of local variables per function to 250, similarly to what Lua does. That gives a bit of wiggle room against off-by-one errors.

**Comment by srijan-paul** [comment]
> Are these limits something that the Pallene compiler should worry about?

Maybe not if it is guaranteed that pallene always compiles with a certain version of gcc that it ships with.
But the lua backend is something that we may want to keep in mind.

> Roberto answered my question in the mailing list. The 255 limit is a hard limit because nupvalues in the ClosureHeader in lobject.h is a byte.

I'll check if this is also true for local variables and the number of constants that there can be in a function. Which reminds me, it might be good to make sure there are useful errors because the lua backend may cause problems if there are too many local vars or constants in a function.

> That gives a bit of wiggle room against off-by-one errors.

Yeah, certainly sounds like the way to go.

**Comment by hugomg** [comment]
Now that we know that the Lua runtime has a hard limit of 255 upvalues, I expect that we will run into this limit before we run into any limits of the C backend.

> the lua backend may cause problems if there are too many local vars or constants in a function.

That's a good point. However, it might take a lot of work to accurately emulate all the limits that the Lua interpreter has. I think it is acceptable if there are some extreme corner cases that work in Pallene but that don't compile in Lua. The Lua back end is primarily there to help test the correctness and the performance of Pallene. But for real-world use, we expect that most people will use the C backend.

Some limits are simple to implement and perhaps it wouldn't hurt to add them to Pallene. For example, we could limit to the number of function arguments. There's no point in allowing people to declare a function with 500 arguments, if Lua will not be able to call it.

However, the other limits might be harder for us to implement. For example, Lua's limit on the number of local variable refers to the number of variables that are in scope at the same time. It's not simply about counting the number of local variable declarations. A function might have more variables than that if some of the variables are in smaller scopes:

```lua
function f()
    do local x1 = true end 
    do local x2 = true end 
    -- ...
    do local x1000 = true end
end
```

There is also the limit for the number of registers, which takes into account the local variables plus the temporary registers used to evaluate expressions. It would be tricky to accurately predict how many registers the Lua interpreter needs for a given function. In my opinion, this would be not worth the trouble.

> Yeah, certainly sounds like the way to go.

Now that I have thought again about what the local variable limit means in Lua, I think I'm no longer a fan of limiting the number of local variables in Pallene. What do you think of this?

* Enforce a limit of 200 function arguments (in the parser)
* Enforce a limit of 200 captured variables (in the to_ir or in one of the closure passes)
* Do not limit the number of local variables inside a Pallene function.

The programs that this does not allow are all programs that Lua also should not allow. But we would allow some programs that are not allowed by the Lua interpreter.

**Comment by srijan-paul** [comment]
> That's a good point. However, it might take a lot of work to accurately emulate all the limits that the Lua interpreter has. I think it is acceptable if there are some extreme corner cases that work in Pallene but that don't compile in Lua.

Reasonable. Code like that is very unlikely to happen too imo. Though there are exceptions like the teal compiler's source file. If it wasn't using tables for maintaining state, it's very easy to hit the limit in rare cases like that. Either way, it makes sense for Pallene to primarily target the C codegen.

>  Enforce a limit of 200 function arguments (in the parser)
>  Enforce a limit of 200 captured variables (in the to_ir or in one of the closure passes)
> Do not limit the number of local variables inside a Pallene function.

I think this ruleset is good.

**Comment by hugomg** [comment]
You know, I had never stopped to think about that for Teal. It turns out that they are very close to the limit. Merely adding a `local x1,x2,x3,x4,x5,x6` to the end is enough to stop it from running.

I'll create separate issues for those limits on function arguments and captured variables. It's likely that we'll implement them in separate PRs.

**Comment by hugomg** [comment]
See #410, #411, and #412.
