### ISSUE TITLE
Toplevel statement ending with ";" is currently forbidden

### ISSUE THREAD

**Issue by srijan-paul** [pallene-lang/pallene#446]
Is it intentional behavior for toplevel statements to not end with semi colons?

```
local m = {};
return m
```
```
test.pln:1:13: unexpected ';' while trying to parse a statement
```

I ask because it's also forbidden in the grammar in [the manual](https://github.com/pallene-lang/pallene/blob/master/doc/manual.md)

```
program ::= {toplevelrecord | topleveltypealias | toplevelvar | toplevelfunc}
```

**Comment by hugomg** [comment]
Yup, they should have allowed semicolons too.
