### ISSUE TITLE
Small test program that can crash Pallene in deep recursion

### ISSUE THREAD

**Issue by ewmailing** [pallene-lang/pallene#550]
This was discussed in the discussion thread: https://github.com/pallene-lang/pallene/discussions/547

Attached is a simple test program (both .pln and .lua files included in .zip) that can crash on my system. I am running Ubuntu 22.04.1 LTS, 64-bit x86-64.

When compiled with Pallene, the program will segfault after the 37380 call:
```
do_something:37380
Segmentation fault (core dumped)
```
Under Lua, the program will abort out with a stack trace much earlier because it goes too deep for Lua.

Ideally, it would be nice if Pallene could terminate a little more gracefully here.

Tidbit: This program did not crash for me until I added return values to do_something(). When it returned nothing, the program ran until completion. I don't know why the return values crashed it, but I was  thinking maybe compiler was able to do some tail recursion optimizations, which could avoid creating a deep call stack. And maybe by adding some return values and a conditional statement, this defeated those optimizations and made the code more vulnerable to segfaulting?

[pallene_stack_overflow_.zip](https://github.com/pallene-lang/pallene/files/9592746/pallene_stack_overflow_.zip)

**Comment by hugomg** [comment]
Fixed by #557
