### ISSUE TITLE
Full pallene stack traces

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#565]
Currently, when a Pallene function calls another Pallene function they share the same Lua stack frams. As a result, if there's a run-time type error, it will show as a single "[C]" function call. 

I imagine three ways that maybe could improve this. The first  would be to make each Pallene function call have it's own Lua stack frame. That way, the default Lua stack trace might be able to show more info.

Another option would be to encode the extra call stack info in the code we generate for function calls. Simillarly to the line number and file name parameter we pass to most internal error subroutines.

A third option would be to rely on C debuggers. Add #line directives everywhere and write a stack take handler that uses gdb to build the stack trace. This would let people avoid the overhead if they compile without -g. Also, it would get rid of the annoying file name and line number function arguments that we mentioned previously. That said relying on an external program such as gdb would add a run-time dependency, which might be undesirable...

**Comment by singul4ri7y** [comment]
Working on it 🚀.

@hugomg  and I initially decided to solve this issue using a separate call stack for Pallene calls, which will be updated for each Pallene to Pallene calls. We also going to have a separate explicit stack-trace function which will take advantage of the separate stack we created, much like [StackTracePlus](https://github.com/ignacio/StackTracePlus).

I also planning to make this this enhanced feature available to other C modules as well, provided that Pallene eventually compiles to C. I will be working on a separate project called **pallene-tracer**, which Pallene will use to get complete stack-trace.

The initial planning doc can be found [here](https://docs.google.com/document/d/1JNMswjvCXlri4nYjLI5f1w3HrkHa7xSKyXSYxNG1MWs/edit#heading=h.hpgwq8lvsj4v).

**Note:** The doc is still in very early stage. It will turn out to be a full documentation related to **pallene-tracer** and this issue in general once I am done. _**Peace.**_
