### ISSUE TITLE
Confusing error message referring to table as function

### ISSUE THREAD

**Issue by bjornbm** [pallene-lang/pallene#581]
```lua
local m = {}
function a:f() end
return m
```

Error message:

```
syntax error: /Users/bjorn/repos/lua/test3.pln:2:1: function 'a' was not forward declared
compilation aborted due to previous error           ^^^^^^^^^^^^
```

In this case, `a` is not a function so the error message is a bit misleading.

Maybe this will “fix itself” once method syntax is implemented, and it is not worth improving the error message in the meantime?

**Comment by hugomg** [comment]
Good catch. Perhaps we should immediately halt with a syntax error when we find method syntax. If we just change the message it's possible that related errors might pop up elsewhere and we'll end up playing whack-a-mole.
