### ISSUE TITLE
Stacktrace: can we avoid xpcall?

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#602]
Should we replace the default traceback in our patched Lua version?

**Comment by hugomg** [comment]
I like the idea of using a wrapper script. That would address the original motivation of not wanting to tell users to edit their source files to insert a xpcall.

I didn't understand the part about copying the contents of the file. I suspect we could make a wrapper script that receives the name of the original Lua script in the command-line arguments and then calls it using `dofile` inside a xpcall.

    pallene-debug main.lua arg1 arg2 arg3

**Comment by singul4ri7y** [comment]
About copying contents of the file: I just meant copying the file :)

The script idea sounds neat 👌.

**Comment by singul4ri7y** [comment]
This issue has been solved by `pt-lua` Lua frontend from [pallene-tracer](https://github.com/pallene-lang/pallene-tracer).
