### ISSUE TITLE
Stop using commands as keys for tables on the garbage collector

### ISSUE THREAD

**Issue by gabrielsferre** [pallene-lang/pallene#610]
We do liveliness analysis to check at each command of the intermediate representation which variables should be saved at the Lua stack before control transfers. Currently, we keep track of live variables per command using a table whose keys are the commands themselves, that is, the ir.Cmd objects: https://github.com/pallene-lang/pallene/blob/57c183789b2b1e0a657a96ce4383c6e6bc5b9e7b/src/pallene/gc.lua#L69-#L88

This approach for indexing the table comes with some aliasing problems (q.v. #575), so we want to replace the table's keys with something else.

**Comment by hugomg** [comment]
In theory, we should be able to index by basic block, like the other analysis.

**Comment by hugomg** [comment]
Done in #615.

@gabrielsferre protip: if you say "closes #615" in the commit message, then github closes the issue automatically
