### ISSUE TITLE
Add function name information to pallene_runtime_arity_error

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#64]
Could be useful, as [suggested](https://github.com/pallene-lang/pallene/pull/61#discussion_r289433523) previously.

We cannot add line-number information because that is not present insice the Lua entry point, but we could in theory add the function name.

Should we do this? How would we handle nested or anonymous functions, in case we add them to pallene in the future?

(A previous version of this comment had it all backwards so I edited it)

**Comment by gligneul** [comment]
> We cannot add line-number information because that is not present insice the Lua entry point, but we could in theory add the function name.

How so?

**Comment by hugomg** [comment]
When we are creating the Lua entry point we know the line number where the function was defined, but not the line number where it was called.
