### ISSUE TITLE
Use udatamemoffset instead of getudatamem

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#66]
Currently our generated code for accessing fields in a C record calls the `getdataumem` macro. I think we might be able to gain a bit of performance if we instead called the `udatamemoffset` macro directly.

```C
/* compute the offset of the memory area of a userdata */
#define udatamemoffset(nuv) \
	((nuv) == 0 ? offsetof(Udata0, bindata)  \
                    : offsetof(Udata, uv) + (sizeof(UValue) * (nuv)))

/* get the address of the memory block inside 'Udata' */
-#define getudatamem(u)	(cast_charp(u) + udatamemoffset((u)->nuvalue))
```

The `getudatamem` macro reads the `->nuvalue` field at runtime. We know at compilation time what value this should be but GCC does not, so it ends up spitting out a bunch of ASM instructions to do the field read and the conditional branch.

I suspect that if we called `udatamemoffset` directly, passing a constant integer literal for the `nuv` parameter, then GCC should be able to compile the field access down to a single mov instruction.

**Comment by gligneul** [comment]
I will do it.
