### ISSUE TITLE
Reduce the length of the extension

### ISSUE THREAD

**Issue by gligneul** [pallene-lang/pallene#72]
I really think that `.pallene` is too lengthy. 
If we don't want conflicts with other languages, we should avoid the following extensions:

- `.p` is used for Pascal
- `.pl` is used for Perl

Some that are short and free to use (in order of preference):

- `.pa`
- `.pln`
- `.pll`
- `.pe`
- `.pn`

**Comment by hugomg** [comment]
I don't feel strongly either way. Among your suggestions, ".pln" is my favourite.

It is used by some applications but no programming languages, afaik
https://fileinfo.com/extension/pln
