### ISSUE TITLE
Check whether the Lua version is compatible with the Pallene module

### ISSUE THREAD

**Issue by gligneul** [pallene-lang/pallene#73]
A Pallene module should be loaded by a particular release of Lua.
We should add a check when the Pallene module is loaded to guarantee that the running version of Lua is the same one that the module was compiled for.
Notice that this should possible include the release (e.g. `5.4.0`), not just the version (e.g. `5.4`).

**Comment by hugomg** [comment]
This is a similar problem to the one we have discussed in #18, about the runtime library version

**Comment by gligneul** [comment]
Yes, it is similar, but a little trickier unless we modify the Lua release that we are using.

**Comment by gligneul** [comment]
Yes, it is similar, but a little trickier unless we modify the Lua release that we are using.

**Comment by hugomg** [comment]
The Lua library provides a lua_version and a luaL_checkversion that verify if the major and minor version numbers match (that is, if we are running Lua 5.4)

Unfortunately, it is not possible to verify the release number (eg. `5.4.0`). It appears in lua.h but it is not used in any C files so it is nowhere to be seen in liblua.so.
