### ISSUE TITLE
Mutually-recursive functions

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#84]
Currently, Pallene does not allow functions to call other functions that are defined further down in the file. I suggest that we allow consecutive function declarations to be mutually-recursive. That is, function declarations are mutually-recursive if there isn't an intervening variable or type declaration between them.

```
local function even(n : integer): boolean
    if n == 0 then
        return true
    else
        return odd(n-1)
    end
end

local function odd(n : integer): boolean
    if n == 0 then
        return false
    else
        return even(n-1)
    end
end
```

Current Lua idioms for mutually-recursive functions are unsatisfactory for Pallene. The first one is to forward-declare local variables:

```
local odd, even
odd = function(n) ... end
even = function(n) ... end
```

The first problem is that Pallene does not allow exporting local variables, so we would need to have  way to tell apart local variables being used in function forward-declarations, and other potentially-mutable local variables. Furthermore this requires adding a bunch of features to the Pallene compiler: uninitialized variables, an optimization pass to determine that odd and even are constants, and are always initialized by the time they are called, and so  on.

The other approach used in Lua is to indirect the function calls through a table:

```
local M = {}
function M.even(n) ... end
function M.odd(n) ... end
```

This is less than ideal in Pallene because it only works for "public" functions, and it requires storing the functions in a table.

**Comment by gligneul** [comment]
> I suggest that we allow consecutive function declarations to be mutually-recursive. That is, function declarations are mutually-recursive if there isn't an intervening variable or type declaration between them.

This is odd because it solves a problem on a very specific way instead of being generic. What if the programmer requires several mutually-recursive functions to implement a parser? Or if the programmer just want to reorder his functions in a way that makes sense for him?

The following case wouldn't work for your proposal, right?
```
function a() ... return b() end
function b() ... return c() end
function c() ... return a() end
```

One idea that I had is add explicit forward declarations, like C function prototypes. These forward declarations would only be present in the top level, which isn't compatible with Lua anyway.

```
forward <name>: <type>
```

This could be a clean placeholder while we don't implement the first option.
Another ideia is bringing back the module letrec, but I guess you don't want that.

**Comment by hugomg** [comment]
> The following case wouldn't work for your proposal, right?

Not only would that work but this is exactly what I amsuggesting :)

> Another ideia is bringing back the module letrec, but I guess you don't want that.

The problem with module-wide letrec is that it potentially allowed module variable initializers to read from other uninitialized variables. (By calling a function that in turn reads from the uninitialized variable).

This is where the "consecutive functions" part comes in. It ensures that functions never use anything that is uninitialized.

> One idea that I had is add explicit forward declarations, like C function prototypes. 

This has the same problems as the "module letrec" approach.

> This could be a clean placeholder while we don't implement the first option.

I don't think we need to settle for a placeholder. The new version of the typechecker that I wrote was written with letrec in mind and it should only require editing a dozen lines or so. It is just that I want to get the coder working first before I go back to that. :)
