### ISSUE TITLE
We should have a spec file that tests pallenec flags

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#87]
Better pallenec test coverage would prevent bugs like the one fixed in #86

**Comment by ahmedkrmn** [comment]
Aren't tests for pallenec implemented in [`/spec/pallenec_spec.lua`](https://github.com/pallene-lang/pallene/blob/master/spec/pallenec_spec.lua) ?

**Comment by hugomg** [comment]
You are right. The reason I opened this issue was because those test cases don't cover the error cases yet, the ones where pallenec calls pallenec_abort.

**Comment by hugomg** [comment]
I think this could be done by adding one or more test cases that call pallenec using `util.outputs_of_execute`, and then check that the error code signals an error, and that the error message is the expected error message.
