### ISSUE TITLE
Update our bundled version of Lua 5.4

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#89]
There have been some new work releases since then.

**Comment by gligneul** [comment]
This will fix the following bug:
```
function main(): nil
    local x: {value} = {}
    return x[10]
end

./pallenec test.pln && ./lua/src/lua -l test -e "print(test.main())"

./lua/src/lua: (command line):1: line 3: wrong type for downcasted value, expected nil but found nil
```

**Comment by hugomg** [comment]
I started investigating this issue.

The first thing that broke is that the `Table` struct no longer has a "sizearray" field. Now there is something else called `alimit`. I need to check with Roberto how this affects us.

https://github.com/lua/lua/blob/9e6807c3c9d5036e999f636f936df07b72284442/lobject.h#L675  
https://github.com/lua/lua/blob/9e6807c3c9d5036e999f636f936df07b72284442/ltable.c#L195
