### ISSUE TITLE
Re-enable -Wmaybe-uninitialized warnings

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#93]
In the current compiler we get -Wmaybe-uninitialized warnings from GCC when it encounters code that looks like the following:

    TValue x1, x2;
    setnilvalue(&x1);
    setobj(L, &x2, &x1);

which after macro expansion becomes something like

    TValue x1, x2;
    x1.tt_ = LUA_TNIL;
    x2.value_ = x1.value_; x2.tt_ = x1->tt_;

which in turn causes GCC to warn that x1.value_ is being read from despite not having been 
initialized.

I worry that GCC might use this undefined behavior to "optimize" our program into crazy nasal demons behavior so if possible I would prefer if the generated code could pass GCC without trigering the warning. Another bonus of enabling the warning is that we would also be able to get rid of "-Wno-unknown-warning-option", which I had to add only becuause clang doesn't itself know about "-Wno-maybe-uninitialized".

Unfortunately, I couldn't think of an easy way to fix the issue right now without hurting performance, so I have disabled the warning despite my fears. However, I have a hunch that the problem might go away by itself once we implement some optimizations that are in the short term roadmap. Namely constant propagation, dead gc-variable stack assignment optimization, and optimizing assignments to arrays of value. Once we finish implementing these optimizations we should check again if the warnings are still there.

**Comment by gligneul** [comment]
We could just initialize the value field when assigning a nil. This shouldn't add a noticeable overhead anyway.
